[package]
name = "github-activity-summarizer"
version = "0.5.1"
edition = "2021"

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
serde = "1.0"
schemars = "0.8"
zed_extension_api = "0.7.0"
