id = "github-activity-summarizer"
name = "GitHub Activity Summarizer"
version = "0.2.2"
schema_version = 1
authors = ["Sergio Rubio rubiojr@rbel.co"]
description = "Summarizes your GitHub activity over a period of time"
repository = "https://github.com/rubiojr/gas"

[context_servers.github-activity-summarizer]
name = "GitHub Activity Summarizer"
