project_name: github-gas-server
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    id: "github-gas-server"
    dir: .
    main: ./cmd/github-gas-server

archives:
  - id: github-gas-server
    format: binary
    name_template: "{{ .Binary }}-{{ .Os }}-{{ .Arch }}"
